### ISSUE TITLE
Did you implement some of these?

### ISSUE THREAD

**Issue by mr2coder** [pettarin/forced-alignment-tools#1]
hello ,Did  you implement some of these? 
I tried to implement some of these, but not one running successfully.
Thanks

**Comment by pettarin** [comment]
Did you mean "install/run" instead of "implement"?

Anyway, if a program is listed in the main table, I was able to install 
it and run it on a Linux (Debian) machine.

Most requires HTK, and most are not easy to setup. By "run" I mean that 
e.g. the included/doc examples work once the tool has been installed. I 
do not make any claim over the actual correctness of their output.

The only exceptions are the tools available as Web applications like 
DARLA, which I did not test but which I added to the table anyway since 
they are widely used in academia.

HTH,

AP

**Comment by mr2coder** [comment]
"most are not easy to setup", that exactly true.....especially in some old linux machine.
The mean of  "implement" here  is train my own language model and run it successfully.
Since you said you can run successfully. I think I should read more document and try again.
Thanks for your reply

**Comment by mr2coder** [comment]
and did you have aeneas' .whl file for python2.7 win10_64bit, I Compiled it failed ?
below is the error message, I already installed MinGW and VCForPython27 and add to the path：
I google this, most of the answer is talking about “c++..link....error ....balabala.”
but.. I only konw a little detail about compilation process....just want to jump from this floor

======== part of error msg ===========
    _Found executable C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.exe
    building 'aeneas.cmfcc.cmfcc' extension
    creating build\temp.win-amd64-3.5\Release\aeneas\cmfcc
    creating build\temp.win-amd64-3.5\Release\aeneas\cwave
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\zjun\appdata\local\programs\python\python35\lib\site-packages\numpy\core\include -I['c:\\users\\zjun\\appdata\\local\\programs\\python\\python35\\lib\\site-packages\\numpy\\core\\include'] -Ic:\users\zjun\appdata\local\programs\python\python35\include -Ic:\users\zjun\appdata\local\programs\python\python35\include -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\8.1\include\shared" -I"C:\Program Files (x86)\Windows Kits\8.1\include\um" -I"C:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcaeneas/cmfcc/cmfcc_py.c /Fobuild\temp.win-amd64-3.5\Release\aeneas/cmfcc/cmfcc_py.obj
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\zjun\appdata\local\programs\python\python35\lib\site-packages\numpy\core\include -I['c:\\users\\zjun\\appdata\\local\\programs\\python\\python35\\lib\\site-packages\\numpy\\core\\include'] -Ic:\users\zjun\appdata\local\programs\python\python35\include -Ic:\users\zjun\appdata\local\programs\python\python35\include -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\8.1\include\shared" -I"C:\Program Files (x86)\Windows Kits\8.1\include\um" -I"C:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcaeneas/cmfcc/cmfcc_func.c /Fobuild\temp.win-amd64-3.5\Release\aeneas/cmfcc/cmfcc_func.obj
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\zjun\appdata\local\programs\python\python35\lib\site-packages\numpy\core\include -I['c:\\users\\zjun\\appdata\\local\\programs\\python\\python35\\lib\\site-packages\\numpy\\core\\include'] -Ic:\users\zjun\appdata\local\programs\python\python35\include -Ic:\users\zjun\appdata\local\programs\python\python35\include -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\8.1\include\shared" -I"C:\Program Files (x86)\Windows Kits\8.1\include\um" -I"C:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcaeneas/cwave/cwave_func.c /Fobuild\temp.win-amd64-3.5\Release\aeneas/cwave/cwave_func.obj
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\zjun\appdata\local\programs\python\python35\lib\site-packages\numpy\core\include -I['c:\\users\\zjun\\appdata\\local\\programs\\python\\python35\\lib\\site-packages\\numpy\\core\\include'] -Ic:\users\zjun\appdata\local\programs\python\python35\include -Ic:\users\zjun\appdata\local\programs\python\python35\include -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\8.1\include\shared" -I"C:\Program Files (x86)\Windows Kits\8.1\include\um" -I"C:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcaeneas/cint/cint.c /Fobuild\temp.win-amd64-3.5\Release\aeneas/cint/cint.obj
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\users\zjun\appdata\local\programs\python\python35\libs /LIBPATH:c:\users\zjun\appdata\local\programs\python\python35\PCbuild\amd64 /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" /EXPORT:PyInit_cmfcc build\temp.win-amd64-3.5\Release\aeneas/cmfcc/cmfcc_py.obj build\temp.win-amd64-3.5\Release\aeneas/cmfcc/cmfcc_func.obj build\temp.win-amd64-3.5\Release\aeneas/cwave/cwave_func.obj build\temp.win-amd64-3.5\Release\aeneas/cint/cint.obj /OUT:build\lib.win-amd64-3.5\aeneas\cmfcc\cmfcc.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\aeneas/cmfcc\cmfcc.cp35-win_amd64.lib
    building 'aeneas.cew.cew' extension
    creating build\temp.win-amd64-3.5\Release\aeneas\cew
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I['c:\\users\\zjun\\appdata\\local\\programs\\python\\python35\\lib\\site-packages\\numpy\\core\\include'] -Ic:\users\zjun\appdata\local\programs\python\python35\include -Ic:\users\zjun\appdata\local\programs\python\python35\include -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\8.1\include\shared" -I"C:\Program Files (x86)\Windows Kits\8.1\include\um" -I"C:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcaeneas/cew/cew_py.c /Fobuild\temp.win-amd64-3.5\Release\aeneas/cew/cew_py.obj
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I['c:\\users\\zjun\\appdata\\local\\programs\\python\\python35\\lib\\site-packages\\numpy\\core\\include'] -Ic:\users\zjun\appdata\local\programs\python\python35\include -Ic:\users\zjun\appdata\local\programs\python\python35\include -I"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" -I"C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" -I"C:\Program Files (x86)\Windows Kits\8.1\include\shared" -I"C:\Program Files (x86)\Windows Kits\8.1\include\um" -I"C:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tcaeneas/cew/cew_func.c /Fobuild\temp.win-amd64-3.5\Release\aeneas/cew/cew_func.obj
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\users\zjun\appdata\local\programs\python\python35\libs /LIBPATH:c:\users\zjun\appdata\local\programs\python\python35\PCbuild\amd64 /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" espeak.lib /EXPORT:PyInit_cew build\temp.win-amd64-3.5\Release\aeneas/cew/cew_py.obj build\temp.win-amd64-3.5\Release\aeneas/cew/cew_func.obj /OUT:build\lib.win-amd64-3.5\aeneas\cew\cew.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\aeneas/cew\cew.cp35-win_amd64.lib
    cew_py.obj : warning LNK4197: export 'PyInit_cew' specified multiple times; using first specification
       Creating library build\temp.win-amd64-3.5\Release\aeneas/cew\cew.cp35-win_amd64.lib and object build\temp.win-amd64-3.5\Release\aeneas/cew\cew.cp35-win_amd64.exp
    cew_func.obj : error LNK2001: unresolved external symbol espeak_Synth
    cew_func.obj : error LNK2001: unresolved external symbol espeak_SetSynthCallback
    cew_func.obj : error LNK2001: unresolved external symbol espeak_SetVoiceByProperties
    cew_func.obj : error LNK2001: unresolved external symbol espeak_Initialize
    cew_func.obj : error LNK2001: unresolved external symbol espeak_Synchronize
    cew_func.obj : error LNK2001: unresolved external symbol espeak_Terminate
    build\lib.win-amd64-3.5\aeneas\cew\cew.cp35-win_amd64.pyd : fatal error LNK1120: 6 unresolved externals
    error: Command "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:c:\users\zjun\appdata\local\programs\python\python35\libs /LIBPATH:c:\users\zjun\appdata\local\programs\python\python35\PCbuild\amd64 /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" espeak.lib /EXPORT:PyInit_cew build\temp.win-amd64-3.5\Release\aeneas/cew/cew_py.obj build\temp.win-amd64-3.5\Release\aeneas/cew/cew_func.obj /OUT:build\lib.win-amd64-3.5\aeneas\cew\cew.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\aeneas/cew\cew.cp35-win_amd64.lib" failed with exit status 1120

    ----------------------------------------
Command "c:\users\zjun\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\zjun\\AppData\\Local\\Temp\\pip-build-hqc9rs26\\aeneas\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\zjun\AppData\Local\Temp\pip-k8d8h19f-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\zjun\AppData\Local\Temp\pip-build-hqc9rs26\aeneas\_

**Comment by pettarin** [comment]
The error indicates that you do not have eSpeak installed and/or pip 
cannot find the espeak.dll when installing aeneas.

Compiling Python C extensions on Windows is tricky. The suggested ways 
of getting aeneas on Windows are 1. the all-in-one installer or 2. the 
VirtualBox+Vagrant virtual machine. Please refer to:

https://github.com/readbeyond/aeneas/blob/master/wiki/INSTALL.md#windows

If you want to discuss the aeneas issue further, please open an Issue on 
the aeneas repository.

I will close this issue the next time I log into GitHub.

HTH,

AP
